name: Centurion
favicon: null
layout_spectrum: 0.37549257138743997
typography_spectrum: 0.520869567990303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#343434'
    - '#202020'
    - '#2b2b2b'
    - '#000000'
    - '#393939'
  brandStrength: 0.75
  lightness: 0.8179828259162605
  saturation: 0.006753937108442187
  rhythmicContrast: 0.4226754871197045
purpose: []
